README.md
Added Description to README file
=> Updated README Description

README.md
=> Initial commit in README file

Main/models/User.js, Main/models/index.js
Added code in Index.js in model
=> Added code in Index.js in model

Main/server.js
=> Added code in serverjs file

seeds/seed.js
Add code and create seeds file with seed.js, User.json and joke.json
=> Add code and create seeds file with seed.js

controllers/api/homeRoutes.js, controllers/api/index.js
Added routes to index and homeRoutes files in the controllers file
=> Added routes to index and homeRoutes files in the controllers file

models/Joke.js, models/User.js
Added code for model in database for user and joke
=> Added code for model in database for user and joke

controllers/api/index.js, controllers/homeRoutes.js, controllers/index.js
Update code in homeRoutes.js and index.js
=> Update code in homeRoutes.js and index.js

controllers/api/jokeRoutes.js
Add code for get jokes by id in JokeRoutesjs file
=> Add code for get jokes by id in JokeRoutesjs file

controllers/api/jokeRoutes.js
Successfully run out get routes for joke
=> Successfully run out get routes for joke

controllers/api/jokeRoutes.js
Successfully run out get by id routes for joke
=> Successfully run out get by id routes for joke

controllers/api/jokeRoutes.js
Successfully run out POST and DELETE routes for joke
=> Successfully run out POST and DELETE routes for joke

controllers/api/userRoutes.js
Successfully run out GET by id routes for users
=> Successfully run out GET by id routes for users

controllers/api/userRoutes.js
Successfully run out POST routes for login logout for USER
=> Successfully run out POST routes for login logout for USER

public/js/profile.js
Add files like add-joke, delete-joke, edit-joke in js
=> Add files like add-joke, delete-joke, edit-joke in js

public/js/add-joke.js, public/js/delete-joke.js, public/js/edit-joke.js
Added code in add-joke, edit-joke, delete-joke in js file
=> Added code in add-joke, edit-joke, delete-joke in js file

public/js/profile.js, views/homepage.handlebars, views/joke.handlebars, views/layouts/main.handlebars, views/login.handlebars, views/profile.handlebars
Update code in handlebars and js, to connect them
=> Update code in handlebars and js, to connect them

public/js/edit-joke.js, views/profile.handlebars
Update code in handlebars and js file to connect them
=> Update code in handlebars and js file to connect them

controllers/api/userRoutes.js, views/login.handlebars
fixed the issue of login, User can login now and users are stored in database using signup button on UI.
=> fixed the issue of login,User can login now

public/js/allJokes.js, views/allJokes.handlebars, views/layouts/main.handlebars
Changed the title for add own joke
=> Changed the title for add own joke

README.md
Added information in README file
=> Added information in README file

controllers/api/jokeRoutes.js, controllers/api/userRoutes.js, controllers/homeRoutes.js, public/css/style.css, public/js/add-joke.js, views/allJokes.handlebars, views/joke.handlebars, views/layouts/main.handlebars
Add code for display all jokes and create new joke(star commit)
=> Add code for display all jokes and create new joke
